// InkTools type definitions for HLSL
// Matches the C# global usings in Types.cs
//
// D2/M0: `ifloat` defaults to FLOAT (storage-float), NOT half. This is deliberate and load-bearing:
// iparticle uses `ifloat` fields, and a StructuredBuffer<iparticle> must have a layout that every backend
// agrees on. M0 grew iparticle to 15 fields; `float` fields are unambiguously 60 bytes on FXC/DXC/Metal/
// Vulkan; `half` fields would be 30 bytes and are only safe where the compiler promotes half in structured
// buffers, which is NOT guaranteed on DX12/mobile. Keeping float preserves the safe 60-byte cross-platform layout.
//
// The switch is CENTRAL and consistent with C# (Types.cs gates the same symbol): flip both sides to half
// via the InkTools > ifloat Mode toggle — the single writer of the generated include (this file's compile-
// time define) AND the matching C# Standalone scripting define — for a future half-vs-float experiment.
// That experiment (D3) must be validated on
// DX11 + DX12 + iOS Metal + Android Vulkan before shipping, because half StructuredBuffer storage/stride
// behaviour differs per backend. Default OFF = float everywhere.

#ifndef INKTOOLS_TYPES_HLSL
#define INKTOOLS_TYPES_HLSL

// CP9f Slice B1: the half/float mode is driven by a single-writer generated include, regenerated by the
// InkTools > ifloat Mode Editor toggle (which also sets the matching C# Standalone scripting define).
// Including it here gives the shader preprocessor a real COMPILE-TIME INKTOOLS_IFLOAT_HALF define — Unity
// C# scripting defines do NOT reach compute shaders. Committed state = float/OFF. Sibling (relative)
// include so it resolves in both the InkTools-own project and any package-consumer project.
#include "InkToolsConfig.generated.hlsl"

#ifdef INKTOOLS_IFLOAT_HALF
    // Experimental 16-bit storage (D3 — requires per-backend validation).
    #define ifloat half
    #define ifloat2 half2
    #define ifloat3 half3
    #define ifloat4 half4
#else
    // Default: storage-float. Guarantees the 60-byte iparticle layout on every backend.
    #define ifloat float
    #define ifloat2 float2
    #define ifloat3 float3
    #define ifloat4 float4
#endif

// idouble types - map to float for mobile performance
#define idouble float
#define idouble2 float2
#define idouble3 float3
#define idouble4 float4
#define idouble4x4 float4x4

#endif // INKTOOLS_TYPES_HLSL