// AUTO-GENERATED by InkToolsIFloatModeToggle — do not edit by hand.
// Single-writer half/float flag for the InkTools ifloat switch (CP9f Slice B1).
// Flip only via InkTools > ifloat Mode, which also sets the C# Standalone scripting define.
#ifndef INKTOOLS_CONFIG_GENERATED_HLSL
#define INKTOOLS_CONFIG_GENERATED_HLSL

#define INKTOOLS_IFLOAT_MODE_HALF 0   // 0 = float (default), 1 = half

// Authoritative shader-side source of truth: clear any preexisting INKTOOLS_IFLOAT_HALF (injected globally
// or by an earlier include) so the 0/1 marker above is the ONLY thing that selects half vs float.
#undef INKTOOLS_IFLOAT_HALF
#if INKTOOLS_IFLOAT_MODE_HALF
#define INKTOOLS_IFLOAT_HALF
#endif

#endif // INKTOOLS_CONFIG_GENERATED_HLSL
